services:
  # Backend
  signoperu-api:
    build: .
    container_name: backend-ia
    ports:
      - "8000:8000"
    restart: always

  # Tunel de Cloudflare
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: tunnel-cloudflare
    # Tu comando con el protocolo http2 para saltar el firewall
    command: tunnel --protocol http2 --no-autoupdate run --token eyJhIjoiMzQzYWZlN2FlN2UzZTE2NWMyZjExM2NlYzMwMjU2MDciLCJ0IjoiZjMzMTUxMjUtZDRlNy00NzA3LWIzN2UtMzIwMzFmODVjYzhiIiwicyI6Ik1qWmtaalF4T0dVdE5tWXdOQzAwWVRnMkxXRmpOelF0WXpCbU9UazVOVE14TXpObSJ9
    restart: always
    depends_on:
      - signoperu-api